require:
  - rubocop-performance
AllCops:
  Exclude:
    - 'gemfiles/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true

Layout/LineLength:
  Max: 150 # TODO: we should decrease this to 120

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 300

Metrics/BlockLength:
  Max: 500

Metrics/MethodLength:
  Max: 100

Metrics/ParameterLists:
  Max: 10

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/ClosingParenthesisIndentation:
  Enabled: false

Style/OneLineConditional:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Not:
  Enabled: false

Documentation:
  Enabled: false # TODO: Enable again once we have more docs

Layout/CaseIndentation:
  EnforcedStyle: case
  SupportedStyles:
    - case
    - end
  IndentOneStep: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': "[]"
    '%W': "[]"

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/SignalException:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Style/TrivialAccessors:
  ExactNameMatch: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/DefEndAlignment:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Performance/RedundantMerge:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Naming/MethodParameterName:
 MinNameLength: 2
