language: ruby

rvm:
  - 2.1
  - 2.2.4
  - 2.3.4
  - 2.4.1
  - ruby-head
  - jruby-9.1.12.0

gemfile:
  - Gemfile

cache: bundler

sudo: false

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

matrix:
  include:
    - rvm: 2.2.4
      gemfile: gemfiles/Gemfile.rails-5.0-master
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.2.4
      gemfile: gemfiles/Gemfile.rails-5.0-master
