language: ruby

rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - jruby-9.1.15.0

gemfile:
  - gemfiles/Gemfile.rest-client.1.8
  - gemfiles/Gemfile.rest-client.2.0
  - gemfiles/Gemfile.rest-client.2.1

cache: bundler

sudo: false

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
